version: '3.1'

services:

  db-car-trade:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - car-trade-network

  adminer-car-trade:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db-car-trade
    networks:
      - car-trade-network

  car-trade:
    image: car-trade
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - TS_NODE_DEV=development
      - DB_CONNECTION=postgres
      - DB_HOST=db-car-trade
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    depends_on:
      - db-car-trade
    networks:
      - car-trade-network

networks:
  car-trade-network:
    driver: bridge
